name: basic-snap-settings
version: git
summary: Set basic snap settings in a user-friendly window.
description: |
  Set basic snap settings in a user-friendly window.
base: core18
confinement: devmode


parts:
  snapsettings:
    plugin: python
    source: .
    build-environment:
      - PYTHONPATH: "invalid"
    build-packages:
      - python3-pip
    stage-packages:
      - libhogweed4
      - libreadline7
      - libnettle6
      - nmcli
      - python3-gi
    stage-snaps:
      - http

apps:
  basic-snap-settings:
    command: bin/basic-snap-settings
    extensions: [gnome-3-28]
