name: basic-snap-settings
version: git
summary: Set basic snap settings in a user-friendly window.
description: |
  Set basic snap settings in a user-friendly window.
base: core20
confinement: devmode


parts:
  snapsettings:
    plugin: python
    source: .
    stage-snaps: [http]

apps:
  basic-snap-settings:
    command: bin/basic-snap-settings
    extensions: [gnome-3-38]
