name: basic-snap-settings
version: '0.3'
summary: Set basic snap settings in a user-friendly window.
description: |
  Set basic snap settings in a user-friendly window.
base: core18
confinement: devmode
grade: stable


parts:
  snapsettings:
    plugin: python
    source: .
    build-environment:
      - PYTHONPATH: "invalid"
    build-packages:
      - python3-pip
    stage-packages:
      - libhogweed4
      - libreadline7
      - libnettle6
      - python3-gi
    stage-snaps:
      - http
      - network-manager

apps:
  basic-snap-settings:
    command: bin/basic-snap-settings
    extensions: [gnome-3-28]
    plugs:
      - network-manager
      - dbus
